Add agat convert genscan2gff
viash-hub/biobox pull request #100
Opened 2024-07-30 11:46 UTC by Leila011

## Description

add  agat_convert_genscan2gff

## Issue ticket number

Closes #xxxx 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

- [ ] Conforms to the [Contributing guidelines](https://github.com/viash-hub/base/blob/main/CONTRIBUTING.md)

- [ ] Proposed changes are described in the [CHANGELOG.md](https://github.com/viash-hub/base/blob/main/CHANGELOG.md)

- [ ] I have tested my code with `viash ns test --parallel -q <name or namespace>`

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Documentation
  - [ ] Bug fixes

2024-08-06 14:04 UTC, Leila011 commented
[agat_convert_genscan2gff source code](https://github.com/NBISweden/AGAT/blob/83641ef2d0a815a783b64f204cac3ed2cec44818/bin/agat_convert_genscan2gff.pl#L289C11-L289C22) names but does not use anywhere the argument `--inflate_off`. Should I open an issue on Agat about it or just remove it from the config file. Or both

Also I am not so sure if `--inflate-off` should be a boolean_false as i initially specified in the config. I wanted to check its behavior in the source code to understand better but well as explain below I could not.

2024-08-10 07:08 UTC, rcannood requested changes

2024-08-13 18:51 UTC, rcannood commented
> [agat_convert_genscan2gff source code](https://github.com/NBISweden/AGAT/blob/83641ef2d0a815a783b64f204cac3ed2cec44818/bin/agat_convert_genscan2gff.pl#L289C11-L289C22) names but does not use anywhere the argument `--inflate_off`. Should I open an issue on Agat about it or just remove it from the config file. Or both
> 
> Also I am not so sure if `--inflate-off` should be a boolean_false as i initially specified in the config. I wanted to check its behavior in the source code to understand better but well as explain below I could not.

Feel free to create a issue for this -- their help file explicitly states so !

Whether you include this argument in the component is up to you :)

2024-09-16 08:17 UTC, rcannood approved these changes

2024-09-16 08:44 UTC, merged