Bedtools_bamtofastq
viash-hub/biobox pull request #101
Opened 2024-07-30 13:41 UTC by tgaspe

## Description

Creating component bedtools_bamtofastq

## Issue ticket number

Closes #xxxx 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

- [ ] Conforms to the [Contributing guidelines](https://github.com/viash-hub/base/blob/main/CONTRIBUTING.md)

- [ ] Proposed changes are described in the [CHANGELOG.md](https://github.com/viash-hub/base/blob/main/CHANGELOG.md)

- [ ] I have tested my code with `viash ns test --parallel -q <name or namespace>`

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Documentation
  - [ ] Bug fixes

2024-08-10 08:13 UTC, rcannood requested changes

2024-08-10 16:29 UTC, tgaspe commented on src/bedtools/bedtools_bamtofastq/config.vsh.yaml
> +      - name: --output_fq2
I think is a good idea.

2024-08-12 09:11 UTC, DriesSchaumont requested changes
Small comment. Don't forget to request another review once you have applied the requested changes (you can do this next by clicking the button next to the name of the reviewer in the revieuwers-section of a PR) :)

2024-08-12 09:11 UTC, DriesSchaumont commented on src/bedtools/bedtools_bamtofastq/script.sh
Please make sure that this script exits on error (I know that there is not a lot of code except for the call to bedtools, but it might be expanded in the future)

2024-08-13 18:38 UTC, rcannood approved these changes
LGTM!

2024-08-13 18:38 UTC, merged