Add agat sp add introns
viash-hub/biobox pull request #104
Opened 2024-07-31 09:43 UTC by Leila011

## Description

add agat_sp_add_introns

Closes #xxxx 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

- [ ] Conforms to the [Contributing guidelines](https://github.com/viash-hub/base/blob/main/CONTRIBUTING.md)

- [ ] Proposed changes are described in the [CHANGELOG.md](https://github.com/viash-hub/base/blob/main/CHANGELOG.md)

- [ ] I have tested my code with `viash ns test --parallel -q <name or namespace>`

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Documentation
  - [ ] Bug fixes

2024-08-12 08:41 UTC, DriesSchaumont requested changes
Small suggestions

2024-08-12 08:41 UTC, DriesSchaumont commented on src/agat/agat_sp_add_introns/config.vsh.yaml
> +  The script aims to add intron features to gtf/gff file without intron features.
```suggestion
  Add intronic elements to a gtf/gff file without intron features.
```

2024-08-12 08:41 UTC, DriesSchaumont commented on src/agat/agat_sp_add_introns/config.vsh.yaml
> +          String - Input agat config file. By default AGAT takes as input agat_config.yaml file from the working directory if any, otherwise it takes the original agat_config.yaml shipped with AGAT.
```suggestion
          Agat config file. By default AGAT takes the original agat_config.yaml shipped with AGAT. The --config option gives you the possibility to use your own AGAT config file (located elsewhere or named differently).
```

2024-08-12 09:00 UTC, DriesSchaumont requested changes

2024-08-12 09:00 UTC, DriesSchaumont commented on src/agat/agat_sp_add_introns/config.vsh.yaml
> +authors:
```suggestion
requirements:
  commands: [agat]
authors:
```

2024-10-26 09:57 UTC, emmarousseau approved these changes
Reduced test data size
Minor changes to config formatting

2024-10-26 13:07 UTC, merged