FastQC
viash-hub/biobox pull request #92
Opened 2024-07-18 21:07 UTC by tgaspe

## Description

Creating FastQC component.

## Issue ticket number

Closes #xxxx 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

- [ ] Conforms to the [Contributing guidelines](https://github.com/viash-hub/base/blob/main/CONTRIBUTING.md)

- [ ] Proposed changes are described in the [CHANGELOG.md](https://github.com/viash-hub/base/blob/main/CHANGELOG.md)

- [ ] I have tested my code with `viash ns test --parallel -q <name or namespace>`

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [x] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Documentation
  - [ ] Bug fixes

2024-07-19 12:34 UTC, tgaspe commented on src/_authors/theodoro_gasperin.yaml
Thanks ;)

2024-07-24 15:57 UTC, rcannood requested changes

2024-07-24 15:57 UTC, rcannood commented on src/fastqc/config.vsh.yaml
> +        example: file
Remove this; Java should be installed in the docker image

2024-07-31 19:13 UTC, rcannood requested changes
ci tests are failing (but error is not caught properly). Can you take a look?

2024-08-01 11:15 UTC, tgaspe commented
Hi Robrecht,

I am not sure I understand which tests are failing?

2024-08-01 11:55 UTC, tgaspe commented
I see, thanks.

2024-08-20 21:16 UTC, rcannood commented on src/fastqc/config.vsh.yaml
> +namespace: fastqc
No need for a namespace if there is just one command

```suggestion
name: fastqc

2024-09-03 08:55 UTC, rcannood approved these changes
LGTM!

2024-09-03 08:55 UTC, merged