Rsem-calculate-expression
viash-hub/biobox pull request #93
Opened 2024-07-24 15:28 UTC by emmarousseau

## Description

RSEM-calculate-expression component

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

- [ ] Conforms to the [Contributing guidelines](https://github.com/viash-hub/base/blob/main/CONTRIBUTING.md)

- [ ] Proposed changes are described in the [CHANGELOG.md](https://github.com/viash-hub/base/blob/main/CHANGELOG.md)

- [ ] I have tested my code with `viash ns test --parallel -q <name or namespace>`

- Check the correct box. Does this PR contain:
  - [ ] Breaking changes
  - [ ] New functionality
  - [ ] Major changes
  - [ ] Minor changes
  - [ ] Documentation
  - [ ] Bug fixes

2024-08-20 05:52 UTC, rcannood commented
Hi @emmarousseau ! Does this PR need more work or is it ready for review? :relaxed:

2024-08-21 18:48 UTC, emmarousseau commented
> Hi @emmarousseau ! Does this PR need more work or is it ready for review? ☺️

Ready now! Let me know if the test data is fine or too big.

2024-08-22 05:11 UTC, rcannood requested changes

2024-08-22 05:11 UTC, rcannood commented on src/rsem/rsem_calculate_expression/test_data/script.sh
> +wget wget https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq3/reference/rsem.tar.gz
Yo dawg I heard you like wget so I put some wget in your wget

2024-08-22 05:11 UTC, rcannood commented on src/rsem/rsem_calculate_expression/test_data/rsem.tar.gz
Unfortunately this is indeed too big :sweat_smile: 

In other components, I just store the fasta and gtf in the test data and build the index inside the unit test. Examples:

* [`star_align_reads`](https://github.com/viash-hub/biobox/blob/main/src/star/star_align_reads/test.sh#L74-L81)
* [`bd_rhapsody_sequence_analysis`](https://github.com/viash-hub/biobox/pull/96/files#diff-dc0e9d57cdd6e0f833ca94e8e8a91cd471a2e5559d37bf3fb63fb6b4acdf5743R30-R54)

This way, we don't need to store a large indexed reference. Could you get this to work here as well?

2024-08-22 05:11 UTC, rcannood commented on src/rsem/rsem_calculate_expression/help.txt
This seems to be empty

2024-09-03 09:27 UTC, rcannood requested changes

2024-09-16 08:04 UTC, rcannood reviewed
Some minor requests!

:crossed_fingers: Should be good to merge afterwards

2024-09-18 13:13 UTC, emmarousseau commented on src/rsem/rsem_calculate_expression/test_data/output/ref.cnt
yep makes sense haha

2024-09-18 13:43 UTC, rcannood approved these changes
LGTM!

2024-09-18 13:45 UTC, merged